[ServiceConfiguration]
Port = "8121"
Debug = false

[LoggerConfiguration]
Filename = "./logs/tg-manager.log"
MaxSize = 10

[PostgresConfiguration]
Host = "postgres"
Port = 5432
User = "pacman"
Password = "MEB3oZZkpxgA1q4WcA10"
DBName = "tg_manager"
SSLMode = "disable"

[TelegramConfiguration]
AppID = 35447762
AppHash = "5d035d8fb6b8d4935f8289b80c5601db"
